In [732]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pandas_profiling import ProfileReport
import numpy as np 
from sklearn.preprocessing import StandardScaler
from kmodes.kprototypes import KPrototypes

In [733]:
data = pd.read_csv("df_par_id.csv")

In [734]:
data

,Unnamed: 0,customer_unique_id,freight_value,review_score,score_freq,price_y,score_rec,score_montant,score_rfm,order_purchase_timestamp,customer_city,order_id,product_id,seller_id,categorie_regroupee
0,0,0000366f3b9a7992bf8c76cfdf3221e2,12.00,5.0,1.0,129.90,4.0,4.0,9.0,2018-05-10 10:56:27,cajamar,e22acc9c116caa3f2b7121bbb380d08e,372645c7439f9661fbbacfd129aa92ec,da8622b14eb17ae2831f4ac5b9dab84a,Mobilier
1,1,0000b849f77a49e4a4ce2b2a4ca5be3f,8.29,4.0,1.0,18.90,4.0,1.0,6.0,2018-05-07 11:11:27,osasco,3594e05a005ac4d06a72673270ef9ec9,5099f7000472b634fea8304448d20825,138dbe45fc62f1e244378131a6801526,Beauté et Santé
2,2,0000f46a3911fa3c0805444483337064,17.22,3.0,1.0,69.00,1.0,2.0,4.0,2017-03-10 21:05:03,sao jose,b33ec3b699337181488304f362a6b734,64b488de448a5324c4134ea39c28a34b,3d871de0142ce09b7081e2b9d1733cb1,Livre et Papeterie
3,3,0000f6ccb0745a6a4b88665a16c9f078,17.63,4.0,1.0,25.99,2.0,1.0,4.0,2017-10-12 20:29:41,belem,41272756ecddd9a9ed0180413cc22fb6,2345a354a6f2033609bbf62bf5be9ef6,ef506c96320abeedfb894c34db06f478,Technologie
4,4,0004aac84e0df4da2b147fca70cf8255,16.89,5.0,1.0,180.00,2.0,5.0,8.0,2017-11-14 19:45:42,sorocaba,d957021f1127559cd947b62533f484f7,c72e18b3fe2739b8d24ebf3102450f37,70a12e78e608ac31179aea7f8422044b,Technologie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94716,94716,fffcf5a5ff07b0908bd4e2dbc735a684,248.71,5.0,1.0,1570.00,1.0,5.0,7.0,2017-06-08 21:00:36,sanharo,725cf8e9c24e679a8a5a32cb92c9ce1e,['bbc5419bc92d76e27795c9ec2c233c64' 'c100e5fef...,17f51e7198701186712e53a39c564617,Beauté et Santé
94717,94717,fffea47cd6d3cc0a88bd621562a9d061,19.69,4.0,1.0,64.89,3.0,2.0,6.0,2017-12-10 20:07:56,feira de santana,c71b9252fd7b3b263aaa4cb09319a323,251876e7ba013b87b7262fb2524e2d60,7aa4334be125fcdd2ba64b3180029f14,Alimentation
94718,94718,ffff371b4d645b6ecea244b27531430a,22.56,5.0,1.0,89.90,1.0,3.0,5.0,2017-02-07 15:49:16,sinop,fdc45e6c7555e6cb3cc0daca2557dbe1,13ad6994bda56edfa0a269e3d9a9acb3,54aa8463e87776b5612f4bdc4bd5d4de,Bricolage et Jardin
94719,94719,ffff5962728ec6157033ef9805bacc48,18.69,5.0,1.0,115.00,4.0,4.0,9.0,2018-05-02 15:17:41,bom jesus do norte,94d3ee0bc2a0af9d4fa47a4d63616e8d,461f43be3bdf8844e65b62d9ac2c7a5a,7d13fca15225358621be4086e1eb0964,Mode
94720,94720,ffffd2657e2aad2907e67c3e9daecbeb,14.57,5.0,1.0,56.99,1.0,2.0,4.0,2017-05-02 20:18:45,campo largo,f79a35da168301ae56922475da21117b,bbaef2eadf31fe3ea6702077398be06c,cc419e0650a3c5ba77189a1882b7556a,Parfumerie

In [735]:
data.customer_unique_id.nunique()

94721

In [736]:
data.columns

Index(['Unnamed: 0', 'customer_unique_id', 'freight_value', 'review_score',
       'score_freq', 'price_y', 'score_rec', 'score_montant', 'score_rfm',
       'order_purchase_timestamp', 'customer_city', 'order_id', 'product_id',
       'seller_id', 'categorie_regroupee'],
      dtype='object')

In [737]:
data

,Unnamed: 0,customer_unique_id,freight_value,review_score,score_freq,price_y,score_rec,score_montant,score_rfm,order_purchase_timestamp,customer_city,order_id,product_id,seller_id,categorie_regroupee
0,0,0000366f3b9a7992bf8c76cfdf3221e2,12.00,5.0,1.0,129.90,4.0,4.0,9.0,2018-05-10 10:56:27,cajamar,e22acc9c116caa3f2b7121bbb380d08e,372645c7439f9661fbbacfd129aa92ec,da8622b14eb17ae2831f4ac5b9dab84a,Mobilier
1,1,0000b849f77a49e4a4ce2b2a4ca5be3f,8.29,4.0,1.0,18.90,4.0,1.0,6.0,2018-05-07 11:11:27,osasco,3594e05a005ac4d06a72673270ef9ec9,5099f7000472b634fea8304448d20825,138dbe45fc62f1e244378131a6801526,Beauté et Santé
2,2,0000f46a3911fa3c0805444483337064,17.22,3.0,1.0,69.00,1.0,2.0,4.0,2017-03-10 21:05:03,sao jose,b33ec3b699337181488304f362a6b734,64b488de448a5324c4134ea39c28a34b,3d871de0142ce09b7081e2b9d1733cb1,Livre et Papeterie
3,3,0000f6ccb0745a6a4b88665a16c9f078,17.63,4.0,1.0,25.99,2.0,1.0,4.0,2017-10-12 20:29:41,belem,41272756ecddd9a9ed0180413cc22fb6,2345a354a6f2033609bbf62bf5be9ef6,ef506c96320abeedfb894c34db06f478,Technologie
4,4,0004aac84e0df4da2b147fca70cf8255,16.89,5.0,1.0,180.00,2.0,5.0,8.0,2017-11-14 19:45:42,sorocaba,d957021f1127559cd947b62533f484f7,c72e18b3fe2739b8d24ebf3102450f37,70a12e78e608ac31179aea7f8422044b,Technologie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94716,94716,fffcf5a5ff07b0908bd4e2dbc735a684,248.71,5.0,1.0,1570.00,1.0,5.0,7.0,2017-06-08 21:00:36,sanharo,725cf8e9c24e679a8a5a32cb92c9ce1e,['bbc5419bc92d76e27795c9ec2c233c64' 'c100e5fef...,17f51e7198701186712e53a39c564617,Beauté et Santé
94717,94717,fffea47cd6d3cc0a88bd621562a9d061,19.69,4.0,1.0,64.89,3.0,2.0,6.0,2017-12-10 20:07:56,feira de santana,c71b9252fd7b3b263aaa4cb09319a323,251876e7ba013b87b7262fb2524e2d60,7aa4334be125fcdd2ba64b3180029f14,Alimentation
94718,94718,ffff371b4d645b6ecea244b27531430a,22.56,5.0,1.0,89.90,1.0,3.0,5.0,2017-02-07 15:49:16,sinop,fdc45e6c7555e6cb3cc0daca2557dbe1,13ad6994bda56edfa0a269e3d9a9acb3,54aa8463e87776b5612f4bdc4bd5d4de,Bricolage et Jardin
94719,94719,ffff5962728ec6157033ef9805bacc48,18.69,5.0,1.0,115.00,4.0,4.0,9.0,2018-05-02 15:17:41,bom jesus do norte,94d3ee0bc2a0af9d4fa47a4d63616e8d,461f43be3bdf8844e65b62d9ac2c7a5a,7d13fca15225358621be4086e1eb0964,Mode
94720,94720,ffffd2657e2aad2907e67c3e9daecbeb,14.57,5.0,1.0,56.99,1.0,2.0,4.0,2017-05-02 20:18:45,campo largo,f79a35da168301ae56922475da21117b,bbaef2eadf31fe3ea6702077398be06c,cc419e0650a3c5ba77189a1882b7556a,Parfumerie

## classer DF d'apres order_purchased_timestamp

In [738]:
data

,Unnamed: 0,customer_unique_id,freight_value,review_score,score_freq,price_y,score_rec,score_montant,score_rfm,order_purchase_timestamp,customer_city,order_id,product_id,seller_id,categorie_regroupee
0,0,0000366f3b9a7992bf8c76cfdf3221e2,12.00,5.0,1.0,129.90,4.0,4.0,9.0,2018-05-10 10:56:27,cajamar,e22acc9c116caa3f2b7121bbb380d08e,372645c7439f9661fbbacfd129aa92ec,da8622b14eb17ae2831f4ac5b9dab84a,Mobilier
1,1,0000b849f77a49e4a4ce2b2a4ca5be3f,8.29,4.0,1.0,18.90,4.0,1.0,6.0,2018-05-07 11:11:27,osasco,3594e05a005ac4d06a72673270ef9ec9,5099f7000472b634fea8304448d20825,138dbe45fc62f1e244378131a6801526,Beauté et Santé
2,2,0000f46a3911fa3c0805444483337064,17.22,3.0,1.0,69.00,1.0,2.0,4.0,2017-03-10 21:05:03,sao jose,b33ec3b699337181488304f362a6b734,64b488de448a5324c4134ea39c28a34b,3d871de0142ce09b7081e2b9d1733cb1,Livre et Papeterie
3,3,0000f6ccb0745a6a4b88665a16c9f078,17.63,4.0,1.0,25.99,2.0,1.0,4.0,2017-10-12 20:29:41,belem,41272756ecddd9a9ed0180413cc22fb6,2345a354a6f2033609bbf62bf5be9ef6,ef506c96320abeedfb894c34db06f478,Technologie
4,4,0004aac84e0df4da2b147fca70cf8255,16.89,5.0,1.0,180.00,2.0,5.0,8.0,2017-11-14 19:45:42,sorocaba,d957021f1127559cd947b62533f484f7,c72e18b3fe2739b8d24ebf3102450f37,70a12e78e608ac31179aea7f8422044b,Technologie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94716,94716,fffcf5a5ff07b0908bd4e2dbc735a684,248.71,5.0,1.0,1570.00,1.0,5.0,7.0,2017-06-08 21:00:36,sanharo,725cf8e9c24e679a8a5a32cb92c9ce1e,['bbc5419bc92d76e27795c9ec2c233c64' 'c100e5fef...,17f51e7198701186712e53a39c564617,Beauté et Santé
94717,94717,fffea47cd6d3cc0a88bd621562a9d061,19.69,4.0,1.0,64.89,3.0,2.0,6.0,2017-12-10 20:07:56,feira de santana,c71b9252fd7b3b263aaa4cb09319a323,251876e7ba013b87b7262fb2524e2d60,7aa4334be125fcdd2ba64b3180029f14,Alimentation
94718,94718,ffff371b4d645b6ecea244b27531430a,22.56,5.0,1.0,89.90,1.0,3.0,5.0,2017-02-07 15:49:16,sinop,fdc45e6c7555e6cb3cc0daca2557dbe1,13ad6994bda56edfa0a269e3d9a9acb3,54aa8463e87776b5612f4bdc4bd5d4de,Bricolage et Jardin
94719,94719,ffff5962728ec6157033ef9805bacc48,18.69,5.0,1.0,115.00,4.0,4.0,9.0,2018-05-02 15:17:41,bom jesus do norte,94d3ee0bc2a0af9d4fa47a4d63616e8d,461f43be3bdf8844e65b62d9ac2c7a5a,7d13fca15225358621be4086e1eb0964,Mode
94720,94720,ffffd2657e2aad2907e67c3e9daecbeb,14.57,5.0,1.0,56.99,1.0,2.0,4.0,2017-05-02 20:18:45,campo largo,f79a35da168301ae56922475da21117b,bbaef2eadf31fe3ea6702077398be06c,cc419e0650a3c5ba77189a1882b7556a,Parfumerie

In [739]:
data["order_purchase_timestamp"] = data["order_purchase_timestamp"].str[:10]

In [740]:
data['order_purchase_timestamp'].dtypes

dtype('O')

In [741]:
data['order_purchase_timestamp'] = pd.to_datetime(data['order_purchase_timestamp'], errors='coerce')

In [742]:
data = data[data['order_purchase_timestamp'].notna()]

In [743]:
data  = data.sort_values('order_purchase_timestamp')

In [744]:
data = data_sorted

In [745]:
data_sorted

,Unnamed: 0,customer_unique_id,freight_value,review_score,score_freq,price_y,score_rec,score_montant,score_rfm,order_purchase_timestamp,customer_city,order_id,product_id,seller_id,categorie_regroupee
68118,68118,b7d76e111c89f7ebf14761390f0f7d17,31.67,1.0,1.0,72.89,1.0,3.0,5.0,2016-09-04,boa vista,2e7a8482f6fb09756ca50c10d7bfc047,['c1488892604e4ba5cff5b4eb4d595400' 'f293394c7...,1554a68530182680ad5c8b042c3ab563,Mobilier
26850,26850,4854e9b3feff728c13ee5fc7d1547e92,15.56,1.0,1.0,59.50,1.0,2.0,4.0,2016-09-05,passo fundo,e5fa5a7210941f7d56d0208e4e071d35,f3c2d01a84c947b078e32bbef0718962,a425f92c199eb576938df686728acd20,Technologie
48626,48626,830d5b7aaa3b6f1e9ad63703bec97d23,2.83,1.0,1.0,134.97,1.0,4.0,6.0,2016-09-15,sao joaquim da barra,bfbd0f9bdef84302105ad712db648a6c,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,Beauté et Santé
5443,5443,0eb1ee9dba87f5b36b4613a65074337c,9.34,1.0,1.0,100.00,1.0,3.0,5.0,2016-10-02,sao paulo,71303d7e93b399f5bcd537d124c0bcfa,d2998d7ced12f83f9b832f33cf6507b6,25e6ffe976bd75618accfe16cefcbd0d,Alimentation
50182,50182,87776adb449c551e74c13fc34f036105,10.96,5.0,1.0,29.99,1.0,1.0,3.0,2016-10-03,taubate,cd3b8574c82b42fc8129f6d502690c3e,e2a1d45a73dc7f5a7f9236b043431b89,b499c00f28f4b7069ff6550af8c1348a,Mode
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12618,12618,21dbe8eabd00b34492a939c540e2b1a7,7.39,5.0,1.0,6.90,5.0,1.0,7.0,2018-08-29,sao paulo,d70442bc5e3cb7438da497cc6a210f80,9a8706b8c060b16e5f0d2925f20bc35b,0be8ff43f22e456b4e0371b2245e4d01,Mode de Vie
65178,65178,afbcfd0b9c5233e7ccc73428526fbb52,7.90,5.0,1.0,457.75,5.0,5.0,11.0,2018-08-29,sao jose dos campos,bee12e8653a04e76786e8891cfb6330a,8d4dac6177fb8134f26fb4c5cc6c0aff,c70c1b0d8ca86052f45a432a38b73958,Beauté et Santé
67822,67822,b701bebbdf478f5500348f03aff62121,8.33,3.0,1.0,24.90,5.0,1.0,7.0,2018-08-29,sao caetano do sul,03ef5dedbe7492bdae72eec50764c43f,c7f27c5bef2338541c772b5776403e6a,7d7866a99a8656a42c7ff6352a433410,Autre
4647,4647,0c6d7218d5f3fa14514fd29865269993,8.45,5.0,1.0,169.80,5.0,4.0,10.0,2018-08-29,sao bernardo do campo,912859fef5a0bd5059b6d48fa79d121a,9865c67a74684715521d1e70226cce0b,fa1c13f2614d7b5c4749cbc52fecda94,Mode
67034,67034,b4dcade04bc548b7e3b0243c801f8c26,7.95,1.0,1.0,99.00,5.0,3.0,9.0,2018-08-29,hortolandia,fb393211459aac00af932cd7ab4fa2cc,b6b76b074ed0d77d0f3443b12d8adb5e,6560211a19b47992c3666cc44a7e94c0,Mode

In [746]:
data_2016 = data[data['order_purchase_timestamp'].dt.year == 2016]
data_2016 = data_2016.sort_values('order_purchase_timestamp')

In [747]:
data_2016 = data_2016.dropna()

In [748]:
data_2016_2017 = data[data['order_purchase_timestamp'].dt.year == (2016 or 2017)]
data_2016_2017 = data.sort_values('order_purchase_timestamp')

In [749]:
data_2016_2017 = data_2016_2017.dropna()

In [750]:
data_2016_2017.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 92791 entries, 68118 to 67034
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                92791 non-null  int64
 1   customer_unique_id        92791 non-null  object
 2   freight_value             92791 non-null  float64
 3   review_score              92791 non-null  float64
 4   score_freq                92791 non-null  float64
 5   price_y                   92791 non-null  float64
 6   score_rec                 92791 non-null  float64
 7   score_montant             92791 non-null  float64
 8   score_rfm                 92791 non-null  float64
 9   order_purchase_timestamp  92791 non-null  datetime64[ns]
 10  customer_city             92791 non-null  object
 11  order_id                  92791 non-null  object
 12  product_id                92791 non-null  object
 13  seller_id                 92791 non-null  object
 14  categorie_regroupee       92791 non-null  object
dtypes: datetime64[ns](1), float64(7), int64(1), object(6)
memory usage: 11.3+ MB

In [751]:
data_pourcent

,Unnamed: 0,customer_unique_id,freight_value,review_score,score_freq,price_y,score_rec,score_montant,score_rfm,order_purchase_timestamp,customer_city,order_id,product_id,seller_id,categorie_regroupee
68118,68118,b7d76e111c89f7ebf14761390f0f7d17,31.67,1.0,1.0,72.89,1.0,3.0,5.0,2016-09-04,boa vista,2e7a8482f6fb09756ca50c10d7bfc047,['c1488892604e4ba5cff5b4eb4d595400' 'f293394c7...,1554a68530182680ad5c8b042c3ab563,Mobilier
26850,26850,4854e9b3feff728c13ee5fc7d1547e92,15.56,1.0,1.0,59.50,1.0,2.0,4.0,2016-09-05,passo fundo,e5fa5a7210941f7d56d0208e4e071d35,f3c2d01a84c947b078e32bbef0718962,a425f92c199eb576938df686728acd20,Technologie
48626,48626,830d5b7aaa3b6f1e9ad63703bec97d23,2.83,1.0,1.0,134.97,1.0,4.0,6.0,2016-09-15,sao joaquim da barra,bfbd0f9bdef84302105ad712db648a6c,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,Beauté et Santé
5443,5443,0eb1ee9dba87f5b36b4613a65074337c,9.34,1.0,1.0,100.00,1.0,3.0,5.0,2016-10-02,sao paulo,71303d7e93b399f5bcd537d124c0bcfa,d2998d7ced12f83f9b832f33cf6507b6,25e6ffe976bd75618accfe16cefcbd0d,Alimentation
50182,50182,87776adb449c551e74c13fc34f036105,10.96,5.0,1.0,29.99,1.0,1.0,3.0,2016-10-03,taubate,cd3b8574c82b42fc8129f6d502690c3e,e2a1d45a73dc7f5a7f9236b043431b89,b499c00f28f4b7069ff6550af8c1348a,Mode
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8943,8943,17eb2dcf3b6c44be06f2212d1cb555cc,17.42,5.0,1.0,69.90,5.0,2.0,8.0,2018-07-18,salvador,cb668af8e8de760052440b117748f7e6,c429a719cac9a29bfb5749d8f9043dae,808d4348b916efa08e766ebad39f61eb,Parfumerie
16557,16557,2c97c0c366a208653fe4cd1b80c7775a,18.98,3.0,1.0,125.20,5.0,4.0,10.0,2018-07-18,jaragua do sul,b394c91714441e1146cc0091a94f99bd,d383c8cc29297315bf72d05f57604055,a1bea7061f61f6fdd9a85a6325ba1033,Bricolage et Jardin
60178,60178,a27b4653c3c45bbb1b1c9f12c91e6c9f,29.71,4.0,1.0,64.99,5.0,2.0,8.0,2018-07-18,sao paulo,bf2910ffd07baa17d7d2ce5a170da758,af91083bde899b201798b52ae89babea,06a2c3af7b3aee5d69171b0e14f0ee87,Beauté et Santé
7717,7717,14967f4bec96864de5c5e2ce63b80bc2,43.29,5.0,1.0,330.00,5.0,5.0,11.0,2018-07-18,juiz de fora,fb49153a4f9a8b019b1a7a058ba8f3e7,9bf850b04e5b1ec3f9e35aaf9a55ce52,5343d0649eca2a983820bfe93fc4d17e,Mobilier
68194,68194,b8043dc7e600706b2f7aa3b8e360f5a4,37.48,5.0,1.0,80.80,5.0,3.0,9.0,2018-07-18,araguaina,31932da1b041c8391eb82c14213e73fb,630e57ced9d2d899f556e0664be676ab,4e17c65a516f69d023a2ae78b84f28d6,Mobilier

In [752]:
data_2016_2017

,Unnamed: 0,customer_unique_id,freight_value,review_score,score_freq,price_y,score_rec,score_montant,score_rfm,order_purchase_timestamp,customer_city,order_id,product_id,seller_id,categorie_regroupee
68118,68118,b7d76e111c89f7ebf14761390f0f7d17,31.67,1.0,1.0,72.89,1.0,3.0,5.0,2016-09-04,boa vista,2e7a8482f6fb09756ca50c10d7bfc047,['c1488892604e4ba5cff5b4eb4d595400' 'f293394c7...,1554a68530182680ad5c8b042c3ab563,Mobilier
26850,26850,4854e9b3feff728c13ee5fc7d1547e92,15.56,1.0,1.0,59.50,1.0,2.0,4.0,2016-09-05,passo fundo,e5fa5a7210941f7d56d0208e4e071d35,f3c2d01a84c947b078e32bbef0718962,a425f92c199eb576938df686728acd20,Technologie
48626,48626,830d5b7aaa3b6f1e9ad63703bec97d23,2.83,1.0,1.0,134.97,1.0,4.0,6.0,2016-09-15,sao joaquim da barra,bfbd0f9bdef84302105ad712db648a6c,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,Beauté et Santé
5443,5443,0eb1ee9dba87f5b36b4613a65074337c,9.34,1.0,1.0,100.00,1.0,3.0,5.0,2016-10-02,sao paulo,71303d7e93b399f5bcd537d124c0bcfa,d2998d7ced12f83f9b832f33cf6507b6,25e6ffe976bd75618accfe16cefcbd0d,Alimentation
50182,50182,87776adb449c551e74c13fc34f036105,10.96,5.0,1.0,29.99,1.0,1.0,3.0,2016-10-03,taubate,cd3b8574c82b42fc8129f6d502690c3e,e2a1d45a73dc7f5a7f9236b043431b89,b499c00f28f4b7069ff6550af8c1348a,Mode
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34329,34329,5c58de6fb80e93396e2f35642666b693,46.48,5.0,1.0,418.00,5.0,5.0,11.0,2018-08-29,curitiba,0b223d92c27432930dfe407c6aea3041,2b4472df15512a2825ae86fd9ae79335,67bf6941ba2f1fa1d02c375766bc3e53,Mobilier
45274,45274,7a22d14aa3c3599238509ddca4b93b01,9.20,1.0,1.0,63.90,5.0,2.0,8.0,2018-08-29,sao paulo,52018484704db3661b98ce838612b507,777798445efd625458a90c13f3b3e6e7,5f2684dab12e59f83bef73ae57724e45,Autre
4647,4647,0c6d7218d5f3fa14514fd29865269993,8.45,5.0,1.0,169.80,5.0,4.0,10.0,2018-08-29,sao bernardo do campo,912859fef5a0bd5059b6d48fa79d121a,9865c67a74684715521d1e70226cce0b,fa1c13f2614d7b5c4749cbc52fecda94,Mode
47461,47461,7febafa06d9d8f232a900a2937f04338,15.39,5.0,1.0,45.90,5.0,2.0,8.0,2018-08-29,paracatu,168626408cb32af0ffaf76711caae1dc,bdcf6a834e8faa30dac3886c7a58e92e,2a84855fd20af891be03bc5924d2b453,Beauté et Santé
67034,67034,b4dcade04bc548b7e3b0243c801f8c26,7.95,1.0,1.0,99.00,5.0,3.0,9.0,2018-08-29,hortolandia,fb393211459aac00af932cd7ab4fa2cc,b6b76b074ed0d77d0f3443b12d8adb5e,6560211a19b47992c3666cc44a7e94c0,Mode

In [753]:
data

,Unnamed: 0,customer_unique_id,freight_value,review_score,score_freq,price_y,score_rec,score_montant,score_rfm,order_purchase_timestamp,customer_city,order_id,product_id,seller_id,categorie_regroupee
68118,68118,b7d76e111c89f7ebf14761390f0f7d17,31.67,1.0,1.0,72.89,1.0,3.0,5.0,2016-09-04,boa vista,2e7a8482f6fb09756ca50c10d7bfc047,['c1488892604e4ba5cff5b4eb4d595400' 'f293394c7...,1554a68530182680ad5c8b042c3ab563,Mobilier
26850,26850,4854e9b3feff728c13ee5fc7d1547e92,15.56,1.0,1.0,59.50,1.0,2.0,4.0,2016-09-05,passo fundo,e5fa5a7210941f7d56d0208e4e071d35,f3c2d01a84c947b078e32bbef0718962,a425f92c199eb576938df686728acd20,Technologie
48626,48626,830d5b7aaa3b6f1e9ad63703bec97d23,2.83,1.0,1.0,134.97,1.0,4.0,6.0,2016-09-15,sao joaquim da barra,bfbd0f9bdef84302105ad712db648a6c,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,Beauté et Santé
5443,5443,0eb1ee9dba87f5b36b4613a65074337c,9.34,1.0,1.0,100.00,1.0,3.0,5.0,2016-10-02,sao paulo,71303d7e93b399f5bcd537d124c0bcfa,d2998d7ced12f83f9b832f33cf6507b6,25e6ffe976bd75618accfe16cefcbd0d,Alimentation
50182,50182,87776adb449c551e74c13fc34f036105,10.96,5.0,1.0,29.99,1.0,1.0,3.0,2016-10-03,taubate,cd3b8574c82b42fc8129f6d502690c3e,e2a1d45a73dc7f5a7f9236b043431b89,b499c00f28f4b7069ff6550af8c1348a,Mode
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12618,12618,21dbe8eabd00b34492a939c540e2b1a7,7.39,5.0,1.0,6.90,5.0,1.0,7.0,2018-08-29,sao paulo,d70442bc5e3cb7438da497cc6a210f80,9a8706b8c060b16e5f0d2925f20bc35b,0be8ff43f22e456b4e0371b2245e4d01,Mode de Vie
65178,65178,afbcfd0b9c5233e7ccc73428526fbb52,7.90,5.0,1.0,457.75,5.0,5.0,11.0,2018-08-29,sao jose dos campos,bee12e8653a04e76786e8891cfb6330a,8d4dac6177fb8134f26fb4c5cc6c0aff,c70c1b0d8ca86052f45a432a38b73958,Beauté et Santé
67822,67822,b701bebbdf478f5500348f03aff62121,8.33,3.0,1.0,24.90,5.0,1.0,7.0,2018-08-29,sao caetano do sul,03ef5dedbe7492bdae72eec50764c43f,c7f27c5bef2338541c772b5776403e6a,7d7866a99a8656a42c7ff6352a433410,Autre
4647,4647,0c6d7218d5f3fa14514fd29865269993,8.45,5.0,1.0,169.80,5.0,4.0,10.0,2018-08-29,sao bernardo do campo,912859fef5a0bd5059b6d48fa79d121a,9865c67a74684715521d1e70226cce0b,fa1c13f2614d7b5c4749cbc52fecda94,Mode
67034,67034,b4dcade04bc548b7e3b0243c801f8c26,7.95,1.0,1.0,99.00,5.0,3.0,9.0,2018-08-29,hortolandia,fb393211459aac00af932cd7ab4fa2cc,b6b76b074ed0d77d0f3443b12d8adb5e,6560211a19b47992c3666cc44a7e94c0,Mode

In [754]:
data_2016_2017

,Unnamed: 0,customer_unique_id,freight_value,review_score,score_freq,price_y,score_rec,score_montant,score_rfm,order_purchase_timestamp,customer_city,order_id,product_id,seller_id,categorie_regroupee
68118,68118,b7d76e111c89f7ebf14761390f0f7d17,31.67,1.0,1.0,72.89,1.0,3.0,5.0,2016-09-04,boa vista,2e7a8482f6fb09756ca50c10d7bfc047,['c1488892604e4ba5cff5b4eb4d595400' 'f293394c7...,1554a68530182680ad5c8b042c3ab563,Mobilier
26850,26850,4854e9b3feff728c13ee5fc7d1547e92,15.56,1.0,1.0,59.50,1.0,2.0,4.0,2016-09-05,passo fundo,e5fa5a7210941f7d56d0208e4e071d35,f3c2d01a84c947b078e32bbef0718962,a425f92c199eb576938df686728acd20,Technologie
48626,48626,830d5b7aaa3b6f1e9ad63703bec97d23,2.83,1.0,1.0,134.97,1.0,4.0,6.0,2016-09-15,sao joaquim da barra,bfbd0f9bdef84302105ad712db648a6c,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,Beauté et Santé
5443,5443,0eb1ee9dba87f5b36b4613a65074337c,9.34,1.0,1.0,100.00,1.0,3.0,5.0,2016-10-02,sao paulo,71303d7e93b399f5bcd537d124c0bcfa,d2998d7ced12f83f9b832f33cf6507b6,25e6ffe976bd75618accfe16cefcbd0d,Alimentation
50182,50182,87776adb449c551e74c13fc34f036105,10.96,5.0,1.0,29.99,1.0,1.0,3.0,2016-10-03,taubate,cd3b8574c82b42fc8129f6d502690c3e,e2a1d45a73dc7f5a7f9236b043431b89,b499c00f28f4b7069ff6550af8c1348a,Mode
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34329,34329,5c58de6fb80e93396e2f35642666b693,46.48,5.0,1.0,418.00,5.0,5.0,11.0,2018-08-29,curitiba,0b223d92c27432930dfe407c6aea3041,2b4472df15512a2825ae86fd9ae79335,67bf6941ba2f1fa1d02c375766bc3e53,Mobilier
45274,45274,7a22d14aa3c3599238509ddca4b93b01,9.20,1.0,1.0,63.90,5.0,2.0,8.0,2018-08-29,sao paulo,52018484704db3661b98ce838612b507,777798445efd625458a90c13f3b3e6e7,5f2684dab12e59f83bef73ae57724e45,Autre
4647,4647,0c6d7218d5f3fa14514fd29865269993,8.45,5.0,1.0,169.80,5.0,4.0,10.0,2018-08-29,sao bernardo do campo,912859fef5a0bd5059b6d48fa79d121a,9865c67a74684715521d1e70226cce0b,fa1c13f2614d7b5c4749cbc52fecda94,Mode
47461,47461,7febafa06d9d8f232a900a2937f04338,15.39,5.0,1.0,45.90,5.0,2.0,8.0,2018-08-29,paracatu,168626408cb32af0ffaf76711caae1dc,bdcf6a834e8faa30dac3886c7a58e92e,2a84855fd20af891be03bc5924d2b453,Beauté et Santé
67034,67034,b4dcade04bc548b7e3b0243c801f8c26,7.95,1.0,1.0,99.00,5.0,3.0,9.0,2018-08-29,hortolandia,fb393211459aac00af932cd7ab4fa2cc,b6b76b074ed0d77d0f3443b12d8adb5e,6560211a19b47992c3666cc44a7e94c0,Mode

In [755]:
n = int(len(data_sorted) * 0.9) # calculate the index of the last row to keep
data_pourcent = data_sorted.iloc[:n, :] # create a new DataFrame with the first 90% of the rows

In [756]:
data_pourcent = data_pourcent.dropna()
data_pourcent = data_pourcent.sort_values('order_purchase_timestamp')

In [757]:
data_pourcent

,Unnamed: 0,customer_unique_id,freight_value,review_score,score_freq,price_y,score_rec,score_montant,score_rfm,order_purchase_timestamp,customer_city,order_id,product_id,seller_id,categorie_regroupee
68118,68118,b7d76e111c89f7ebf14761390f0f7d17,31.67,1.0,1.0,72.89,1.0,3.0,5.0,2016-09-04,boa vista,2e7a8482f6fb09756ca50c10d7bfc047,['c1488892604e4ba5cff5b4eb4d595400' 'f293394c7...,1554a68530182680ad5c8b042c3ab563,Mobilier
26850,26850,4854e9b3feff728c13ee5fc7d1547e92,15.56,1.0,1.0,59.50,1.0,2.0,4.0,2016-09-05,passo fundo,e5fa5a7210941f7d56d0208e4e071d35,f3c2d01a84c947b078e32bbef0718962,a425f92c199eb576938df686728acd20,Technologie
48626,48626,830d5b7aaa3b6f1e9ad63703bec97d23,2.83,1.0,1.0,134.97,1.0,4.0,6.0,2016-09-15,sao joaquim da barra,bfbd0f9bdef84302105ad712db648a6c,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,Beauté et Santé
5443,5443,0eb1ee9dba87f5b36b4613a65074337c,9.34,1.0,1.0,100.00,1.0,3.0,5.0,2016-10-02,sao paulo,71303d7e93b399f5bcd537d124c0bcfa,d2998d7ced12f83f9b832f33cf6507b6,25e6ffe976bd75618accfe16cefcbd0d,Alimentation
50182,50182,87776adb449c551e74c13fc34f036105,10.96,5.0,1.0,29.99,1.0,1.0,3.0,2016-10-03,taubate,cd3b8574c82b42fc8129f6d502690c3e,e2a1d45a73dc7f5a7f9236b043431b89,b499c00f28f4b7069ff6550af8c1348a,Mode
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8943,8943,17eb2dcf3b6c44be06f2212d1cb555cc,17.42,5.0,1.0,69.90,5.0,2.0,8.0,2018-07-18,salvador,cb668af8e8de760052440b117748f7e6,c429a719cac9a29bfb5749d8f9043dae,808d4348b916efa08e766ebad39f61eb,Parfumerie
16557,16557,2c97c0c366a208653fe4cd1b80c7775a,18.98,3.0,1.0,125.20,5.0,4.0,10.0,2018-07-18,jaragua do sul,b394c91714441e1146cc0091a94f99bd,d383c8cc29297315bf72d05f57604055,a1bea7061f61f6fdd9a85a6325ba1033,Bricolage et Jardin
60178,60178,a27b4653c3c45bbb1b1c9f12c91e6c9f,29.71,4.0,1.0,64.99,5.0,2.0,8.0,2018-07-18,sao paulo,bf2910ffd07baa17d7d2ce5a170da758,af91083bde899b201798b52ae89babea,06a2c3af7b3aee5d69171b0e14f0ee87,Beauté et Santé
7717,7717,14967f4bec96864de5c5e2ce63b80bc2,43.29,5.0,1.0,330.00,5.0,5.0,11.0,2018-07-18,juiz de fora,fb49153a4f9a8b019b1a7a058ba8f3e7,9bf850b04e5b1ec3f9e35aaf9a55ce52,5343d0649eca2a983820bfe93fc4d17e,Mobilier
68194,68194,b8043dc7e600706b2f7aa3b8e360f5a4,37.48,5.0,1.0,80.80,5.0,3.0,9.0,2018-07-18,araguaina,31932da1b041c8391eb82c14213e73fb,630e57ced9d2d899f556e0664be676ab,4e17c65a516f69d023a2ae78b84f28d6,Mobilier

In [758]:
n

83511

In [759]:
data.order_purchase_timestamp.unique()

array(['2016-09-04T00:00:00.000000000', '2016-09-05T00:00:00.000000000',
       '2016-09-15T00:00:00.000000000', '2016-10-02T00:00:00.000000000',
       '2016-10-03T00:00:00.000000000', '2016-10-04T00:00:00.000000000',
       '2016-10-05T00:00:00.000000000', '2016-10-06T00:00:00.000000000',
       '2016-10-07T00:00:00.000000000', '2016-10-08T00:00:00.000000000',
       '2016-10-09T00:00:00.000000000', '2016-10-10T00:00:00.000000000',
       '2017-01-05T00:00:00.000000000', '2017-01-06T00:00:00.000000000',
       '2017-01-07T00:00:00.000000000', '2017-01-08T00:00:00.000000000',
       '2017-01-09T00:00:00.000000000', '2017-01-10T00:00:00.000000000',
       '2017-01-11T00:00:00.000000000', '2017-01-12T00:00:00.000000000',
       '2017-01-13T00:00:00.000000000', '2017-01-14T00:00:00.000000000',
       '2017-01-15T00:00:00.000000000', '2017-01-16T00:00:00.000000000',
       '2017-01-17T00:00:00.000000000', '2017-01-18T00:00:00.000000000',
       '2017-01-19T00:00:00.000000000', '2017-01-20T00:00:00.000000000',
       '2017-01-21T00:00:00.000000000', '2017-01-22T00:00:00.000000000',
       '2017-01-23T00:00:00.000000000', '2017-01-24T00:00:00.000000000',
       '2017-01-25T00:00:00.000000000', '2017-01-26T00:00:00.000000000',
       '2017-01-27T00:00:00.000000000', '2017-01-28T00:00:00.000000000',
       '2017-01-29T00:00:00.000000000', '2017-01-30T00:00:00.000000000',
       '2017-01-31T00:00:00.000000000', '2017-02-01T00:00:00.000000000',
       '2017-02-02T00:00:00.000000000', '2017-02-03T00:00:00.000000000',
       '2017-02-04T00:00:00.000000000', '2017-02-05T00:00:00.000000000',
       '2017-02-06T00:00:00.000000000', '2017-02-07T00:00:00.000000000',
       '2017-02-08T00:00:00.000000000', '2017-02-09T00:00:00.000000000',
       '2017-02-10T00:00:00.000000000', '2017-02-11T00:00:00.000000000',
       '2017-02-12T00:00:00.000000000', '2017-02-13T00:00:00.000000000',
       '2017-02-14T00:00:00.000000000', '2017-02-15T00:00:00.000000000',
       '2017-02-16T00:00:00.000000000', '2017-02-17T00:00:00.000000000',
       '2017-02-18T00:00:00.000000000', '2017-02-19T00:00:00.000000000',
       '2017-02-20T00:00:00.000000000', '2017-02-21T00:00:00.000000000',
       '2017-02-22T00:00:00.000000000', '2017-02-23T00:00:00.000000000',
       '2017-02-24T00:00:00.000000000', '2017-02-25T00:00:00.000000000',
       '2017-02-26T00:00:00.000000000', '2017-02-27T00:00:00.000000000',
       '2017-02-28T00:00:00.000000000', '2017-03-01T00:00:00.000000000',
       '2017-03-02T00:00:00.000000000', '2017-03-03T00:00:00.000000000',
       '2017-03-04T00:00:00.000000000', '2017-03-05T00:00:00.000000000',
       '2017-03-06T00:00:00.000000000', '2017-03-07T00:00:00.000000000',
       '2017-03-08T00:00:00.000000000', '2017-03-09T00:00:00.000000000',
       '2017-03-10T00:00:00.000000000', '2017-03-11T00:00:00.000000000',
       '2017-03-12T00:00:00.000000000', '2017-03-13T00:00:00.000000000',
       '2017-03-14T00:00:00.000000000', '2017-03-15T00:00:00.000000000',
       '2017-03-16T00:00:00.000000000', '2017-03-17T00:00:00.000000000',
       '2017-03-18T00:00:00.000000000', '2017-03-19T00:00:00.000000000',
       '2017-03-20T00:00:00.000000000', '2017-03-21T00:00:00.000000000',
       '2017-03-22T00:00:00.000000000', '2017-03-23T00:00:00.000000000',
       '2017-03-24T00:00:00.000000000', '2017-03-25T00:00:00.000000000',
       '2017-03-26T00:00:00.000000000', '2017-03-27T00:00:00.000000000',
       '2017-03-28T00:00:00.000000000', '2017-03-29T00:00:00.000000000',
       '2017-03-30T00:00:00.000000000', '2017-03-31T00:00:00.000000000',
       '2017-04-01T00:00:00.000000000', '2017-04-02T00:00:00.000000000',
       '2017-04-03T00:00:00.000000000', '2017-04-04T00:00:00.000000000',
       '2017-04-05T00:00:00.000000000', '2017-04-06T00:00:00.000000000',
       '2017-04-07T00:00:00.000000000', '2017-04-08T00:00:00.000000000',
       '2017-04-09T00:00:00.000000000', '2017-04-10T00:00:00.000000000',
       '2017-04-11T00:00:00.000000000', '2017-04-12T00:00:00.000000000',
       '2017-04-13T00:00:00.000000000', '2017-04-14T00:00:00.000000000',
       '2017-04-15T00:00:00.000000000', '2017-04-16T00:00:00.000000000',
       '2017-04-17T00:00:00.000000000', '2017-04-18T00:00:00.000000000',
       '2017-04-19T00:00:00.000000000', '2017-04-20T00:00:00.000000000',
       '2017-04-21T00:00:00.000000000', '2017-04-22T00:00:00.000000000',
       '2017-04-23T00:00:00.000000000', '2017-04-24T00:00:00.000000000',
       '2017-04-25T00:00:00.000000000', '2017-04-26T00:00:00.000000000',
       '2017-04-27T00:00:00.000000000', '2017-04-28T00:00:00.000000000',
       '2017-04-29T00:00:00.000000000', '2017-04-30T00:00:00.000000000',
       '2017-05-01T00:00:00.000000000', '2017-05-02T00:00:00.000000000',
       '2017-05-03T00:00:00.000000000', '2017-05-04T00:00:00.000000000',
       '2017-05-05T00:00:00.000000000', '2017-05-06T00:00:00.000000000',
       '2017-05-07T00:00:00.000000000', '2017-05-08T00:00:00.000000000',
       '2017-05-09T00:00:00.000000000', '2017-05-10T00:00:00.000000000',
       '2017-05-11T00:00:00.000000000', '2017-05-12T00:00:00.000000000',
       '2017-05-13T00:00:00.000000000', '2017-05-14T00:00:00.000000000',
       '2017-05-15T00:00:00.000000000', '2017-05-16T00:00:00.000000000',
       '2017-05-17T00:00:00.000000000', '2017-05-18T00:00:00.000000000',
       '2017-05-19T00:00:00.000000000', '2017-05-20T00:00:00.000000000',
       '2017-05-21T00:00:00.000000000', '2017-05-22T00:00:00.000000000',
       '2017-05-23T00:00:00.000000000', '2017-05-24T00:00:00.000000000',
       '2017-05-25T00:00:00.000000000', '2017-05-26T00:00:00.000000000',
       '2017-05-27T00:00:00.000000000', '2017-05-28T00:00:00.000000000',
       '2017-05-29T00:00:00.000000000', '2017-05-30T00:00:00.000000000',
       '2017-05-31T00:00:00.000000000', '2017-06-01T00:00:00.000000000',
       '2017-06-02T00:00:00.000000000', '2017-06-03T00:00:00.000000000',
       '2017-06-04T00:00:00.000000000', '2017-06-05T00:00:00.000000000',
       '2017-06-06T00:00:00.000000000', '2017-06-07T00:00:00.000000000',
       '2017-06-08T00:00:00.000000000', '2017-06-09T00:00:00.000000000',
       '2017-06-10T00:00:00.000000000', '2017-06-11T00:00:00.000000000',
       '2017-06-12T00:00:00.000000000', '2017-06-13T00:00:00.000000000',
       '2017-06-14T00:00:00.000000000', '2017-06-15T00:00:00.000000000',
       '2017-06-16T00:00:00.000000000', '2017-06-17T00:00:00.000000000',
       '2017-06-18T00:00:00.000000000', '2017-06-19T00:00:00.000000000',
       '2017-06-20T00:00:00.000000000', '2017-06-21T00:00:00.000000000',
       '2017-06-22T00:00:00.000000000', '2017-06-23T00:00:00.000000000',
       '2017-06-24T00:00:00.000000000', '2017-06-25T00:00:00.000000000',
       '2017-06-26T00:00:00.000000000', '2017-06-27T00:00:00.000000000',
       '2017-06-28T00:00:00.000000000', '2017-06-29T00:00:00.000000000',
       '2017-06-30T00:00:00.000000000', '2017-07-01T00:00:00.000000000',
       '2017-07-02T00:00:00.000000000', '2017-07-03T00:00:00.000000000',
       '2017-07-04T00:00:00.000000000', '2017-07-05T00:00:00.000000000',
       '2017-07-06T00:00:00.000000000', '2017-07-07T00:00:00.000000000',
       '2017-07-08T00:00:00.000000000', '2017-07-09T00:00:00.000000000',
       '2017-07-10T00:00:00.000000000', '2017-07-11T00:00:00.000000000',
       '2017-07-12T00:00:00.000000000', '2017-07-13T00:00:00.000000000',
       '2017-07-14T00:00:00.000000000', '2017-07-15T00:00:00.000000000',
       '2017-07-16T00:00:00.000000000', '2017-07-17T00:00:00.000000000',
       '2017-07-18T00:00:00.000000000', '2017-07-19T00:00:00.000000000',
       '2017-07-20T00:00:00.000000000', '2017-07-21T00:00:00.000000000',
       '2017-07-22T00:00:00.000000000', '2017-07-23T00:00:00.000000000',
       '2017-07-24T00:00:00.000000000', '2017-07-25T00:00:00.000000000',
       '2017-07-26T00:00:00.000000000', '2017-07-27T00:00:00.000000000',
       '2017-07-28T00:00:00.000000000', '2017-07-29T00:00:00.000000000',
       '2017-07-30T00:00:00.000000000', '2017-07-31T00:00:00.000000000',
       '2017-08-01T00:00:00.000000000', '2017-08-02T00:00:00.000000000',
       '2017-08-03T00:00:00.000000000', '2017-08-04T00:00:00.000000000',
       '2017-08-05T00:00:00.000000000', '2017-08-06T00:00:00.000000000',
       '2017-08-07T00:00:00.000000000', '2017-08-08T00:00:00.000000000',
       '2017-08-09T00:00:00.000000000', '2017-08-10T00:00:00.000000000',
       '2017-08-11T00:00:00.000000000', '2017-08-12T00:00:00.000000000',
       '2017-08-13T00:00:00.000000000', '2017-08-14T00:00:00.000000000',
       '2017-08-15T00:00:00.000000000', '2017-08-16T00:00:00.000000000',
       '2017-08-17T00:00:00.000000000', '2017-08-18T00:00:00.000000000',
       '2017-08-19T00:00:00.000000000', '2017-08-20T00:00:00.000000000',
       '2017-08-21T00:00:00.000000000', '2017-08-22T00:00:00.000000000',
       '2017-08-23T00:00:00.000000000', '2017-08-24T00:00:00.000000000',
       '2017-08-25T00:00:00.000000000', '2017-08-26T00:00:00.000000000',
       '2017-08-27T00:00:00.000000000', '2017-08-28T00:00:00.000000000',
       '2017-08-29T00:00:00.000000000', '2017-08-30T00:00:00.000000000',
       '2017-08-31T00:00:00.000000000', '2017-09-01T00:00:00.000000000',
       '2017-09-02T00:00:00.000000000', '2017-09-03T00:00:00.000000000',
       '2017-09-04T00:00:00.000000000', '2017-09-05T00:00:00.000000000',
       '2017-09-06T00:00:00.000000000', '2017-09-07T00:00:00.000000000',
       '2017-09-08T00:00:00.000000000', '2017-09-09T00:00:00.000000000',
       '2017-09-10T00:00:00.000000000', '2017-09-11T00:00:00.000000000',
       '2017-09-12T00:00:00.000000000', '2017-09-13T00:00:00.000000000',
       '2017-09-14T00:00:00.000000000', '2017-09-15T00:00:00.000000000',
       '2017-09-16T00:00:00.000000000', '2017-09-17T00:00:00.000000000',
       '2017-09-18T00:00:00.000000000', '2017-09-19T00:00:00.000000000',
       '2017-09-20T00:00:00.000000000', '2017-09-21T00:00:00.000000000',
       '2017-09-22T00:00:00.000000000', '2017-09-23T00:00:00.000000000',
       '2017-09-24T00:00:00.000000000', '2017-09-25T00:00:00.000000000',
       '2017-09-26T00:00:00.000000000', '2017-09-27T00:00:00.000000000',
       '2017-09-28T00:00:00.000000000', '2017-09-29T00:00:00.000000000',
       '2017-09-30T00:00:00.000000000', '2017-10-01T00:00:00.000000000',
       '2017-10-02T00:00:00.000000000', '2017-10-03T00:00:00.000000000',
       '2017-10-04T00:00:00.000000000', '2017-10-05T00:00:00.000000000',
       '2017-10-06T00:00:00.000000000', '2017-10-07T00:00:00.000000000',
       '2017-10-08T00:00:00.000000000', '2017-10-09T00:00:00.000000000',
       '2017-10-10T00:00:00.000000000', '2017-10-11T00:00:00.000000000',
       '2017-10-12T00:00:00.000000000', '2017-10-13T00:00:00.000000000',
       '2017-10-14T00:00:00.000000000', '2017-10-15T00:00:00.000000000',
       '2017-10-16T00:00:00.000000000', '2017-10-17T00:00:00.000000000',
       '2017-10-18T00:00:00.000000000', '2017-10-19T00:00:00.000000000',
       '2017-10-20T00:00:00.000000000', '2017-10-21T00:00:00.000000000',
       '2017-10-22T00:00:00.000000000', '2017-10-23T00:00:00.000000000',
       '2017-10-24T00:00:00.000000000', '2017-10-25T00:00:00.000000000',
       '2017-10-26T00:00:00.000000000', '2017-10-27T00:00:00.000000000',
       '2017-10-28T00:00:00.000000000', '2017-10-29T00:00:00.000000000',
       '2017-10-30T00:00:00.000000000', '2017-10-31T00:00:00.000000000',
       '2017-11-01T00:00:00.000000000', '2017-11-02T00:00:00.000000000',
       '2017-11-03T00:00:00.000000000', '2017-11-04T00:00:00.000000000',
       '2017-11-05T00:00:00.000000000', '2017-11-06T00:00:00.000000000',
       '2017-11-07T00:00:00.000000000', '2017-11-08T00:00:00.000000000',
       '2017-11-09T00:00:00.000000000', '2017-11-10T00:00:00.000000000',
       '2017-11-11T00:00:00.000000000', '2017-11-12T00:00:00.000000000',
       '2017-11-13T00:00:00.000000000', '2017-11-14T00:00:00.000000000',
       '2017-11-15T00:00:00.000000000', '2017-11-16T00:00:00.000000000',
       '2017-11-17T00:00:00.000000000', '2017-11-18T00:00:00.000000000',
       '2017-11-19T00:00:00.000000000', '2017-11-20T00:00:00.000000000',
       '2017-11-21T00:00:00.000000000', '2017-11-22T00:00:00.000000000',
       '2017-11-23T00:00:00.000000000', '2017-11-24T00:00:00.000000000',
       '2017-11-25T00:00:00.000000000', '2017-11-26T00:00:00.000000000',
       '2017-11-27T00:00:00.000000000', '2017-11-28T00:00:00.000000000',
       '2017-11-29T00:00:00.000000000', '2017-11-30T00:00:00.000000000',
       '2017-12-01T00:00:00.000000000', '2017-12-02T00:00:00.000000000',
       '2017-12-03T00:00:00.000000000', '2017-12-04T00:00:00.000000000',
       '2017-12-05T00:00:00.000000000', '2017-12-06T00:00:00.000000000',
       '2017-12-07T00:00:00.000000000', '2017-12-08T00:00:00.000000000',
       '2017-12-09T00:00:00.000000000', '2017-12-10T00:00:00.000000000',
       '2017-12-11T00:00:00.000000000', '2017-12-12T00:00:00.000000000',
       '2017-12-13T00:00:00.000000000', '2017-12-14T00:00:00.000000000',
       '2017-12-15T00:00:00.000000000', '2017-12-16T00:00:00.000000000',
       '2017-12-17T00:00:00.000000000', '2017-12-18T00:00:00.000000000',
       '2017-12-19T00:00:00.000000000', '2017-12-20T00:00:00.000000000',
       '2017-12-21T00:00:00.000000000', '2017-12-22T00:00:00.000000000',
       '2017-12-23T00:00:00.000000000', '2017-12-24T00:00:00.000000000',
       '2017-12-25T00:00:00.000000000', '2017-12-26T00:00:00.000000000',
       '2017-12-27T00:00:00.000000000', '2017-12-28T00:00:00.000000000',
       '2017-12-29T00:00:00.000000000', '2017-12-30T00:00:00.000000000',
       '2017-12-31T00:00:00.000000000', '2018-01-01T00:00:00.000000000',
       '2018-01-02T00:00:00.000000000', '2018-01-03T00:00:00.000000000',
       '2018-01-04T00:00:00.000000000', '2018-01-05T00:00:00.000000000',
       '2018-01-06T00:00:00.000000000', '2018-01-07T00:00:00.000000000',
       '2018-01-08T00:00:00.000000000', '2018-01-09T00:00:00.000000000',
       '2018-01-10T00:00:00.000000000', '2018-01-11T00:00:00.000000000',
       '2018-01-12T00:00:00.000000000', '2018-01-13T00:00:00.000000000',
       '2018-01-14T00:00:00.000000000', '2018-01-15T00:00:00.000000000',
       '2018-01-16T00:00:00.000000000', '2018-01-17T00:00:00.000000000',
       '2018-01-18T00:00:00.000000000', '2018-01-19T00:00:00.000000000',
       '2018-01-20T00:00:00.000000000', '2018-01-21T00:00:00.000000000',
       '2018-01-22T00:00:00.000000000', '2018-01-23T00:00:00.000000000',
       '2018-01-24T00:00:00.000000000', '2018-01-25T00:00:00.000000000',
       '2018-01-26T00:00:00.000000000', '2018-01-27T00:00:00.000000000',
       '2018-01-28T00:00:00.000000000', '2018-01-29T00:00:00.000000000',
       '2018-01-30T00:00:00.000000000', '2018-01-31T00:00:00.000000000',
       '2018-02-01T00:00:00.000000000', '2018-02-02T00:00:00.000000000',
       '2018-02-03T00:00:00.000000000', '2018-02-04T00:00:00.000000000',
       '2018-02-05T00:00:00.000000000', '2018-02-06T00:00:00.000000000',
       '2018-02-07T00:00:00.000000000', '2018-02-08T00:00:00.000000000',
       '2018-02-09T00:00:00.000000000', '2018-02-10T00:00:00.000000000',
       '2018-02-11T00:00:00.000000000', '2018-02-12T00:00:00.000000000',
       '2018-02-13T00:00:00.000000000', '2018-02-14T00:00:00.000000000',
       '2018-02-15T00:00:00.000000000', '2018-02-16T00:00:00.000000000',
       '2018-02-17T00:00:00.000000000', '2018-02-18T00:00:00.000000000',
       '2018-02-19T00:00:00.000000000', '2018-02-20T00:00:00.000000000',
       '2018-02-21T00:00:00.000000000', '2018-02-22T00:00:00.000000000',
       '2018-02-23T00:00:00.000000000', '2018-02-24T00:00:00.000000000',
       '2018-02-25T00:00:00.000000000', '2018-02-26T00:00:00.000000000',
       '2018-02-27T00:00:00.000000000', '2018-02-28T00:00:00.000000000',
       '2018-03-01T00:00:00.000000000', '2018-03-02T00:00:00.000000000',
       '2018-03-03T00:00:00.000000000', '2018-03-04T00:00:00.000000000',
       '2018-03-05T00:00:00.000000000', '2018-03-06T00:00:00.000000000',
       '2018-03-07T00:00:00.000000000', '2018-03-08T00:00:00.000000000',
       '2018-03-09T00:00:00.000000000', '2018-03-10T00:00:00.000000000',
       '2018-03-11T00:00:00.000000000', '2018-03-12T00:00:00.000000000',
       '2018-03-13T00:00:00.000000000', '2018-03-14T00:00:00.000000000',
       '2018-03-15T00:00:00.000000000', '2018-03-16T00:00:00.000000000',
       '2018-03-17T00:00:00.000000000', '2018-03-18T00:00:00.000000000',
       '2018-03-19T00:00:00.000000000', '2018-03-20T00:00:00.000000000',
       '2018-03-21T00:00:00.000000000', '2018-03-22T00:00:00.000000000',
       '2018-03-23T00:00:00.000000000', '2018-03-24T00:00:00.000000000',
       '2018-03-25T00:00:00.000000000', '2018-03-26T00:00:00.000000000',
       '2018-03-27T00:00:00.000000000', '2018-03-28T00:00:00.000000000',
       '2018-03-29T00:00:00.000000000', '2018-03-30T00:00:00.000000000',
       '2018-03-31T00:00:00.000000000', '2018-04-01T00:00:00.000000000',
       '2018-04-02T00:00:00.000000000', '2018-04-03T00:00:00.000000000',
       '2018-04-04T00:00:00.000000000', '2018-04-05T00:00:00.000000000',
       '2018-04-06T00:00:00.000000000', '2018-04-07T00:00:00.000000000',
       '2018-04-08T00:00:00.000000000', '2018-04-09T00:00:00.000000000',
       '2018-04-10T00:00:00.000000000', '2018-04-11T00:00:00.000000000',
       '2018-04-12T00:00:00.000000000', '2018-04-13T00:00:00.000000000',
       '2018-04-14T00:00:00.000000000', '2018-04-15T00:00:00.000000000',
       '2018-04-16T00:00:00.000000000', '2018-04-17T00:00:00.000000000',
       '2018-04-18T00:00:00.000000000', '2018-04-19T00:00:00.000000000',
       '2018-04-20T00:00:00.000000000', '2018-04-21T00:00:00.000000000',
       '2018-04-22T00:00:00.000000000', '2018-04-23T00:00:00.000000000',
       '2018-04-24T00:00:00.000000000', '2018-04-25T00:00:00.000000000',
       '2018-04-26T00:00:00.000000000', '2018-04-27T00:00:00.000000000',
       '2018-04-28T00:00:00.000000000', '2018-04-29T00:00:00.000000000',
       '2018-04-30T00:00:00.000000000', '2018-05-01T00:00:00.000000000',
       '2018-05-02T00:00:00.000000000', '2018-05-03T00:00:00.000000000',
       '2018-05-04T00:00:00.000000000', '2018-05-05T00:00:00.000000000',
       '2018-05-06T00:00:00.000000000', '2018-05-07T00:00:00.000000000',
       '2018-05-08T00:00:00.000000000', '2018-05-09T00:00:00.000000000',
       '2018-05-10T00:00:00.000000000', '2018-05-11T00:00:00.000000000',
       '2018-05-12T00:00:00.000000000', '2018-05-13T00:00:00.000000000',
       '2018-05-14T00:00:00.000000000', '2018-05-15T00:00:00.000000000',
       '2018-05-16T00:00:00.000000000', '2018-05-17T00:00:00.000000000',
       '2018-05-18T00:00:00.000000000', '2018-05-19T00:00:00.000000000',
       '2018-05-20T00:00:00.000000000', '2018-05-21T00:00:00.000000000',
       '2018-05-22T00:00:00.000000000', '2018-05-23T00:00:00.000000000',
       '2018-05-24T00:00:00.000000000', '2018-05-25T00:00:00.000000000',
       '2018-05-26T00:00:00.000000000', '2018-05-27T00:00:00.000000000',
       '2018-05-28T00:00:00.000000000', '2018-05-29T00:00:00.000000000',
       '2018-05-30T00:00:00.000000000', '2018-05-31T00:00:00.000000000',
       '2018-06-01T00:00:00.000000000', '2018-06-02T00:00:00.000000000',
       '2018-06-03T00:00:00.000000000', '2018-06-04T00:00:00.000000000',
       '2018-06-05T00:00:00.000000000', '2018-06-06T00:00:00.000000000',
       '2018-06-07T00:00:00.000000000', '2018-06-08T00:00:00.000000000',
       '2018-06-09T00:00:00.000000000', '2018-06-10T00:00:00.000000000',
       '2018-06-11T00:00:00.000000000', '2018-06-12T00:00:00.000000000',
       '2018-06-13T00:00:00.000000000', '2018-06-14T00:00:00.000000000',
       '2018-06-15T00:00:00.000000000', '2018-06-16T00:00:00.000000000',
       '2018-06-17T00:00:00.000000000', '2018-06-18T00:00:00.000000000',
       '2018-06-19T00:00:00.000000000', '2018-06-20T00:00:00.000000000',
       '2018-06-21T00:00:00.000000000', '2018-06-22T00:00:00.000000000',

In [760]:
# drop la date pour chaque dataframe

In [761]:
data.dtypes

Unnamed: 0                           int64
customer_unique_id                  object
freight_value                      float64
review_score                       float64
score_freq                         float64
price_y                            float64
score_rec                          float64
score_montant                      float64
score_rfm                          float64
order_purchase_timestamp    datetime64[ns]
customer_city                       object
order_id                            object
product_id                          object
seller_id                           object
categorie_regroupee                 object
dtype: object

In [762]:
data = data.dropna()

In [763]:
missing_values = data.isnull().sum()
print(missing_values)

Unnamed: 0                  0
customer_unique_id          0
freight_value               0
review_score                0
score_freq                  0
price_y                     0
score_rec                   0
score_montant               0
score_rfm                   0
order_purchase_timestamp    0
customer_city               0
order_id                    0
product_id                  0
seller_id                   0
categorie_regroupee         0
dtype: int64

### K prototypes

In [764]:

import numpy as np
import pandas as pd
from kmodes.kprototypes import KPrototypes

# sélectionner les colonnes numériques et catégorielles
numeric_cols = [col for col in data.columns if data[col].dtype in [np.float64, np.int64]]
categorical_cols = [col for col in data.columns if data[col].dtype == 'object']

# séparer les colonnes numériques et catégorielles dans deux dataframes distincts
numeric_data = data[numeric_cols]
categorical_data = data[categorical_cols]




# standardiser les colonnes numériques


# combiner les deux dataframes (numériques et catégorielles)
data_combined = pd.concat([numeric_data, categorical_data], axis=1)

# initialiser l'algorithme K-Prototypes avec les paramètres nécessaires

In [765]:
kproto = KPrototypes(n_clusters=5, init='Huang',n_jobs = -1 , max_iter = 20, n_init=2, verbose=2,random_state=42)

 # entraîner le modèle sur les données combinées
clusters = kproto.fit_predict(data_combined, categorical=list(range(len(numeric_cols), data_combined.shape[1])))

# afficher les résultats
print("Cluster labels:", clusters)

Init: initializing centroids
Init: initializing centroids
Init: initializing clusters
Init: initializing clusters
Starting iterations...
Starting iterations...
Run: 2, iteration: 1/20, moves: 12381, ncost: 3092010618189.1587
Run: 1, iteration: 1/20, moves: 20893, ncost: 3292343596310.8667
Run: 2, iteration: 2/20, moves: 5520, ncost: 2943897898196.6914
Run: 1, iteration: 2/20, moves: 11140, ncost: 2887981675515.707
Run: 2, iteration: 3/20, moves: 3444, ncost: 2881575070616.153
Run: 1, iteration: 3/20, moves: 5214, ncost: 2802987866624.296
Run: 2, iteration: 4/20, moves: 2677, ncost: 2846745946355.138
Run: 1, iteration: 4/20, moves: 2404, ncost: 2785237354922.042
Run: 2, iteration: 5/20, moves: 2192, ncost: 2824709192145.331
Run: 1, iteration: 5/20, moves: 1035, ncost: 2781710143834.667
Run: 1, iteration: 6/20, moves: 495, ncost: 2780864809536.998
Run: 2, iteration: 6/20, moves: 1808, ncost: 2810137551753.925
Run: 1, iteration: 7/20, moves: 225, ncost: 2780662702641.723
Run: 2, iteration: 7/20, moves: 1464, ncost: 2800517042825.6553
Run: 1, iteration: 8/20, moves: 111, ncost: 2780597355685.4194
Run: 2, iteration: 8/20, moves: 1200, ncost: 2794113527349.4155
Run: 1, iteration: 9/20, moves: 79, ncost: 2780566326524.826
Run: 2, iteration: 9/20, moves: 988, ncost: 2789713995004.6567
Run: 1, iteration: 10/20, moves: 66, ncost: 2780548045908.2583
Run: 2, iteration: 10/20, moves: 828, ncost: 2786705029617.208
Run: 1, iteration: 11/20, moves: 45, ncost: 2780538290235.726
Run: 2, iteration: 11/20, moves: 666, ncost: 2784695629596.3975
Run: 1, iteration: 12/20, moves: 41, ncost: 2780530544728.0225
Run: 2, iteration: 12/20, moves: 557, ncost: 2783306379515.8555
Run: 1, iteration: 13/20, moves: 35, ncost: 2780524899791.571
Run: 2, iteration: 13/20, moves: 448, ncost: 2782417742120.871
Run: 1, iteration: 14/20, moves: 29, ncost: 2780521676851.3423
Run: 2, iteration: 14/20, moves: 357, ncost: 2781814039542.552
Run: 1, iteration: 15/20, moves: 18, ncost: 2780519899185.093
Run: 2, iteration: 15/20, moves: 302, ncost: 2781398104182.037
Run: 1, iteration: 16/20, moves: 17, ncost: 2780518741722.418
Run: 2, iteration: 16/20, moves: 245, ncost: 2781113439950.3394
Run: 1, iteration: 17/20, moves: 8, ncost: 2780518444365.134
Run: 2, iteration: 17/20, moves: 199, ncost: 2780923816500.2666
Run: 1, iteration: 18/20, moves: 8, ncost: 2780518150399.9766
Run: 2, iteration: 18/20, moves: 169, ncost: 2780792244848.0283
Run: 1, iteration: 19/20, moves: 5, ncost: 2780517972097.2153
Run: 2, iteration: 19/20, moves: 151, ncost: 2780695056299.905
Run: 1, iteration: 20/20, moves: 7, ncost: 2780517767300.6494
Run: 2, iteration: 20/20, moves: 132, ncost: 2780625813980.2236
Best run was number 1
Cluster labels: [0 3 4 ... 0 1 0]

In [766]:
data_combined

,Unnamed: 0,freight_value,review_score,score_freq,price_y,score_rec,score_montant,score_rfm,customer_unique_id,customer_city,order_id,product_id,seller_id,categorie_regroupee
68118,68118,31.67,1.0,1.0,72.89,1.0,3.0,5.0,b7d76e111c89f7ebf14761390f0f7d17,boa vista,2e7a8482f6fb09756ca50c10d7bfc047,['c1488892604e4ba5cff5b4eb4d595400' 'f293394c7...,1554a68530182680ad5c8b042c3ab563,Mobilier
26850,26850,15.56,1.0,1.0,59.50,1.0,2.0,4.0,4854e9b3feff728c13ee5fc7d1547e92,passo fundo,e5fa5a7210941f7d56d0208e4e071d35,f3c2d01a84c947b078e32bbef0718962,a425f92c199eb576938df686728acd20,Technologie
48626,48626,2.83,1.0,1.0,134.97,1.0,4.0,6.0,830d5b7aaa3b6f1e9ad63703bec97d23,sao joaquim da barra,bfbd0f9bdef84302105ad712db648a6c,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,Beauté et Santé
5443,5443,9.34,1.0,1.0,100.00,1.0,3.0,5.0,0eb1ee9dba87f5b36b4613a65074337c,sao paulo,71303d7e93b399f5bcd537d124c0bcfa,d2998d7ced12f83f9b832f33cf6507b6,25e6ffe976bd75618accfe16cefcbd0d,Alimentation
50182,50182,10.96,5.0,1.0,29.99,1.0,1.0,3.0,87776adb449c551e74c13fc34f036105,taubate,cd3b8574c82b42fc8129f6d502690c3e,e2a1d45a73dc7f5a7f9236b043431b89,b499c00f28f4b7069ff6550af8c1348a,Mode
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12618,12618,7.39,5.0,1.0,6.90,5.0,1.0,7.0,21dbe8eabd00b34492a939c540e2b1a7,sao paulo,d70442bc5e3cb7438da497cc6a210f80,9a8706b8c060b16e5f0d2925f20bc35b,0be8ff43f22e456b4e0371b2245e4d01,Mode de Vie
65178,65178,7.90,5.0,1.0,457.75,5.0,5.0,11.0,afbcfd0b9c5233e7ccc73428526fbb52,sao jose dos campos,bee12e8653a04e76786e8891cfb6330a,8d4dac6177fb8134f26fb4c5cc6c0aff,c70c1b0d8ca86052f45a432a38b73958,Beauté et Santé
67822,67822,8.33,3.0,1.0,24.90,5.0,1.0,7.0,b701bebbdf478f5500348f03aff62121,sao caetano do sul,03ef5dedbe7492bdae72eec50764c43f,c7f27c5bef2338541c772b5776403e6a,7d7866a99a8656a42c7ff6352a433410,Autre
4647,4647,8.45,5.0,1.0,169.80,5.0,4.0,10.0,0c6d7218d5f3fa14514fd29865269993,sao bernardo do campo,912859fef5a0bd5059b6d48fa79d121a,9865c67a74684715521d1e70226cce0b,fa1c13f2614d7b5c4749cbc52fecda94,Mode
67034,67034,7.95,1.0,1.0,99.00,5.0,3.0,9.0,b4dcade04bc548b7e3b0243c801f8c26,hortolandia,fb393211459aac00af932cd7ab4fa2cc,b6b76b074ed0d77d0f3443b12d8adb5e,6560211a19b47992c3666cc44a7e94c0,Mode

In [767]:
clusters

array([0, 3, 4, ..., 0, 1, 0], dtype=uint16)

In [768]:
data_combined["cluster"] = clusters

In [769]:
data_combined

,Unnamed: 0,freight_value,review_score,score_freq,price_y,score_rec,score_montant,score_rfm,customer_unique_id,customer_city,order_id,product_id,seller_id,categorie_regroupee,cluster
68118,68118,31.67,1.0,1.0,72.89,1.0,3.0,5.0,b7d76e111c89f7ebf14761390f0f7d17,boa vista,2e7a8482f6fb09756ca50c10d7bfc047,['c1488892604e4ba5cff5b4eb4d595400' 'f293394c7...,1554a68530182680ad5c8b042c3ab563,Mobilier,0
26850,26850,15.56,1.0,1.0,59.50,1.0,2.0,4.0,4854e9b3feff728c13ee5fc7d1547e92,passo fundo,e5fa5a7210941f7d56d0208e4e071d35,f3c2d01a84c947b078e32bbef0718962,a425f92c199eb576938df686728acd20,Technologie,3
48626,48626,2.83,1.0,1.0,134.97,1.0,4.0,6.0,830d5b7aaa3b6f1e9ad63703bec97d23,sao joaquim da barra,bfbd0f9bdef84302105ad712db648a6c,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,Beauté et Santé,4
5443,5443,9.34,1.0,1.0,100.00,1.0,3.0,5.0,0eb1ee9dba87f5b36b4613a65074337c,sao paulo,71303d7e93b399f5bcd537d124c0bcfa,d2998d7ced12f83f9b832f33cf6507b6,25e6ffe976bd75618accfe16cefcbd0d,Alimentation,1
50182,50182,10.96,5.0,1.0,29.99,1.0,1.0,3.0,87776adb449c551e74c13fc34f036105,taubate,cd3b8574c82b42fc8129f6d502690c3e,e2a1d45a73dc7f5a7f9236b043431b89,b499c00f28f4b7069ff6550af8c1348a,Mode,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12618,12618,7.39,5.0,1.0,6.90,5.0,1.0,7.0,21dbe8eabd00b34492a939c540e2b1a7,sao paulo,d70442bc5e3cb7438da497cc6a210f80,9a8706b8c060b16e5f0d2925f20bc35b,0be8ff43f22e456b4e0371b2245e4d01,Mode de Vie,1
65178,65178,7.90,5.0,1.0,457.75,5.0,5.0,11.0,afbcfd0b9c5233e7ccc73428526fbb52,sao jose dos campos,bee12e8653a04e76786e8891cfb6330a,8d4dac6177fb8134f26fb4c5cc6c0aff,c70c1b0d8ca86052f45a432a38b73958,Beauté et Santé,0
67822,67822,8.33,3.0,1.0,24.90,5.0,1.0,7.0,b701bebbdf478f5500348f03aff62121,sao caetano do sul,03ef5dedbe7492bdae72eec50764c43f,c7f27c5bef2338541c772b5776403e6a,7d7866a99a8656a42c7ff6352a433410,Autre,0
4647,4647,8.45,5.0,1.0,169.80,5.0,4.0,10.0,0c6d7218d5f3fa14514fd29865269993,sao bernardo do campo,912859fef5a0bd5059b6d48fa79d121a,9865c67a74684715521d1e70226cce0b,fa1c13f2614d7b5c4749cbc52fecda94,Mode,1
67034,67034,7.95,1.0,1.0,99.00,5.0,3.0,9.0,b4dcade04bc548b7e3b0243c801f8c26,hortolandia,fb393211459aac00af932cd7ab4fa2cc,b6b76b074ed0d77d0f3443b12d8adb5e,6560211a19b47992c3666cc44a7e94c0,Mode,0

In [770]:
#numeric_data["cluster"] = clusters

In [771]:
#data["cluster"] = clusters

In [772]:
data

,Unnamed: 0,customer_unique_id,freight_value,review_score,score_freq,price_y,score_rec,score_montant,score_rfm,order_purchase_timestamp,customer_city,order_id,product_id,seller_id,categorie_regroupee
68118,68118,b7d76e111c89f7ebf14761390f0f7d17,31.67,1.0,1.0,72.89,1.0,3.0,5.0,2016-09-04,boa vista,2e7a8482f6fb09756ca50c10d7bfc047,['c1488892604e4ba5cff5b4eb4d595400' 'f293394c7...,1554a68530182680ad5c8b042c3ab563,Mobilier
26850,26850,4854e9b3feff728c13ee5fc7d1547e92,15.56,1.0,1.0,59.50,1.0,2.0,4.0,2016-09-05,passo fundo,e5fa5a7210941f7d56d0208e4e071d35,f3c2d01a84c947b078e32bbef0718962,a425f92c199eb576938df686728acd20,Technologie
48626,48626,830d5b7aaa3b6f1e9ad63703bec97d23,2.83,1.0,1.0,134.97,1.0,4.0,6.0,2016-09-15,sao joaquim da barra,bfbd0f9bdef84302105ad712db648a6c,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,Beauté et Santé
5443,5443,0eb1ee9dba87f5b36b4613a65074337c,9.34,1.0,1.0,100.00,1.0,3.0,5.0,2016-10-02,sao paulo,71303d7e93b399f5bcd537d124c0bcfa,d2998d7ced12f83f9b832f33cf6507b6,25e6ffe976bd75618accfe16cefcbd0d,Alimentation
50182,50182,87776adb449c551e74c13fc34f036105,10.96,5.0,1.0,29.99,1.0,1.0,3.0,2016-10-03,taubate,cd3b8574c82b42fc8129f6d502690c3e,e2a1d45a73dc7f5a7f9236b043431b89,b499c00f28f4b7069ff6550af8c1348a,Mode
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12618,12618,21dbe8eabd00b34492a939c540e2b1a7,7.39,5.0,1.0,6.90,5.0,1.0,7.0,2018-08-29,sao paulo,d70442bc5e3cb7438da497cc6a210f80,9a8706b8c060b16e5f0d2925f20bc35b,0be8ff43f22e456b4e0371b2245e4d01,Mode de Vie
65178,65178,afbcfd0b9c5233e7ccc73428526fbb52,7.90,5.0,1.0,457.75,5.0,5.0,11.0,2018-08-29,sao jose dos campos,bee12e8653a04e76786e8891cfb6330a,8d4dac6177fb8134f26fb4c5cc6c0aff,c70c1b0d8ca86052f45a432a38b73958,Beauté et Santé
67822,67822,b701bebbdf478f5500348f03aff62121,8.33,3.0,1.0,24.90,5.0,1.0,7.0,2018-08-29,sao caetano do sul,03ef5dedbe7492bdae72eec50764c43f,c7f27c5bef2338541c772b5776403e6a,7d7866a99a8656a42c7ff6352a433410,Autre
4647,4647,0c6d7218d5f3fa14514fd29865269993,8.45,5.0,1.0,169.80,5.0,4.0,10.0,2018-08-29,sao bernardo do campo,912859fef5a0bd5059b6d48fa79d121a,9865c67a74684715521d1e70226cce0b,fa1c13f2614d7b5c4749cbc52fecda94,Mode
67034,67034,b4dcade04bc548b7e3b0243c801f8c26,7.95,1.0,1.0,99.00,5.0,3.0,9.0,2018-08-29,hortolandia,fb393211459aac00af932cd7ab4fa2cc,b6b76b074ed0d77d0f3443b12d8adb5e,6560211a19b47992c3666cc44a7e94c0,Mode

In [773]:
""" from sklearn.manifold import TSNE

# create the t-SNE object with the desired parameters
tsne = TSNE()

# fit and transform the data
reduced_data = tsne.fit_transform(numeric_data)
 """

' from sklearn.manifold import TSNE\n\n# create the t-SNE object with the desired parameters\ntsne = TSNE()\n\n# fit and transform the data\nreduced_data = tsne.fit_transform(numeric_data)\n '

In [774]:
numeric_data

,Unnamed: 0,freight_value,review_score,score_freq,price_y,score_rec,score_montant,score_rfm
68118,68118,31.67,1.0,1.0,72.89,1.0,3.0,5.0
26850,26850,15.56,1.0,1.0,59.50,1.0,2.0,4.0
48626,48626,2.83,1.0,1.0,134.97,1.0,4.0,6.0
5443,5443,9.34,1.0,1.0,100.00,1.0,3.0,5.0
50182,50182,10.96,5.0,1.0,29.99,1.0,1.0,3.0
...,...,...,...,...,...,...,...,...
12618,12618,7.39,5.0,1.0,6.90,5.0,1.0,7.0
65178,65178,7.90,5.0,1.0,457.75,5.0,5.0,11.0
67822,67822,8.33,3.0,1.0,24.90,5.0,1.0,7.0
4647,4647,8.45,5.0,1.0,169.80,5.0,4.0,10.0
67034,67034,7.95,1.0,1.0,99.00,5.0,3.0,9.0

In [775]:
""" # plot the transformed data
plt.scatter(reduced_data[:, 0], reduced_data[:, 1], c=numeric_data["score_montant"])
plt.xlabel("t-SNE Dimension 1")
plt.ylabel("t-SNE Dimension 2") """

' # plot the transformed data\nplt.scatter(reduced_data[:, 0], reduced_data[:, 1], c=numeric_data["score_montant"])\nplt.xlabel("t-SNE Dimension 1")\nplt.ylabel("t-SNE Dimension 2") '

In [776]:
""" plt.scatter(reduced_data[:, 0], reduced_data[:, 1], c=numeric_data["cluster"])
plt.xlabel("t-SNE Dimension 1")
plt.ylabel("t-SNE Dimension 2") """

' plt.scatter(reduced_data[:, 0], reduced_data[:, 1], c=numeric_data["cluster"])\nplt.xlabel("t-SNE Dimension 1")\nplt.ylabel("t-SNE Dimension 2") '

In [777]:
data.to_csv("df_cluster_test.csv")

In [778]:
data

,Unnamed: 0,customer_unique_id,freight_value,review_score,score_freq,price_y,score_rec,score_montant,score_rfm,order_purchase_timestamp,customer_city,order_id,product_id,seller_id,categorie_regroupee
68118,68118,b7d76e111c89f7ebf14761390f0f7d17,31.67,1.0,1.0,72.89,1.0,3.0,5.0,2016-09-04,boa vista,2e7a8482f6fb09756ca50c10d7bfc047,['c1488892604e4ba5cff5b4eb4d595400' 'f293394c7...,1554a68530182680ad5c8b042c3ab563,Mobilier
26850,26850,4854e9b3feff728c13ee5fc7d1547e92,15.56,1.0,1.0,59.50,1.0,2.0,4.0,2016-09-05,passo fundo,e5fa5a7210941f7d56d0208e4e071d35,f3c2d01a84c947b078e32bbef0718962,a425f92c199eb576938df686728acd20,Technologie
48626,48626,830d5b7aaa3b6f1e9ad63703bec97d23,2.83,1.0,1.0,134.97,1.0,4.0,6.0,2016-09-15,sao joaquim da barra,bfbd0f9bdef84302105ad712db648a6c,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,Beauté et Santé
5443,5443,0eb1ee9dba87f5b36b4613a65074337c,9.34,1.0,1.0,100.00,1.0,3.0,5.0,2016-10-02,sao paulo,71303d7e93b399f5bcd537d124c0bcfa,d2998d7ced12f83f9b832f33cf6507b6,25e6ffe976bd75618accfe16cefcbd0d,Alimentation
50182,50182,87776adb449c551e74c13fc34f036105,10.96,5.0,1.0,29.99,1.0,1.0,3.0,2016-10-03,taubate,cd3b8574c82b42fc8129f6d502690c3e,e2a1d45a73dc7f5a7f9236b043431b89,b499c00f28f4b7069ff6550af8c1348a,Mode
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12618,12618,21dbe8eabd00b34492a939c540e2b1a7,7.39,5.0,1.0,6.90,5.0,1.0,7.0,2018-08-29,sao paulo,d70442bc5e3cb7438da497cc6a210f80,9a8706b8c060b16e5f0d2925f20bc35b,0be8ff43f22e456b4e0371b2245e4d01,Mode de Vie
65178,65178,afbcfd0b9c5233e7ccc73428526fbb52,7.90,5.0,1.0,457.75,5.0,5.0,11.0,2018-08-29,sao jose dos campos,bee12e8653a04e76786e8891cfb6330a,8d4dac6177fb8134f26fb4c5cc6c0aff,c70c1b0d8ca86052f45a432a38b73958,Beauté et Santé
67822,67822,b701bebbdf478f5500348f03aff62121,8.33,3.0,1.0,24.90,5.0,1.0,7.0,2018-08-29,sao caetano do sul,03ef5dedbe7492bdae72eec50764c43f,c7f27c5bef2338541c772b5776403e6a,7d7866a99a8656a42c7ff6352a433410,Autre
4647,4647,0c6d7218d5f3fa14514fd29865269993,8.45,5.0,1.0,169.80,5.0,4.0,10.0,2018-08-29,sao bernardo do campo,912859fef5a0bd5059b6d48fa79d121a,9865c67a74684715521d1e70226cce0b,fa1c13f2614d7b5c4749cbc52fecda94,Mode
67034,67034,b4dcade04bc548b7e3b0243c801f8c26,7.95,1.0,1.0,99.00,5.0,3.0,9.0,2018-08-29,hortolandia,fb393211459aac00af932cd7ab4fa2cc,b6b76b074ed0d77d0f3443b12d8adb5e,6560211a19b47992c3666cc44a7e94c0,Mode

In [779]:
# mise a jour , ARI

In [780]:
from sklearn.metrics.cluster import adjusted_rand_score

In [781]:
data_2016 = data_2016.dropna()

In [782]:
data_2016.columns

Index(['Unnamed: 0', 'customer_unique_id', 'freight_value', 'review_score',
       'score_freq', 'price_y', 'score_rec', 'score_montant', 'score_rfm',
       'order_purchase_timestamp', 'customer_city', 'order_id', 'product_id',
       'seller_id', 'categorie_regroupee'],
      dtype='object')

In [783]:
data_2016 = data_2016[[ 'freight_value', 'review_score', 'score_freq', 'score_rec',
        'score_montant', 
       'customer_city', 'categorie_regroupee']]

In [784]:
import numpy as np
import pandas as pd
from kmodes.kprototypes import KPrototypes

# sélectionner les colonnes numériques et catégorielles
numeric_cols = [col for col in data_2016.columns if data_2016[col].dtype in [np.float64, np.int64]]
categorical_cols = [col for col in data_2016.columns if data_2016[col].dtype == 'object']

# séparer les colonnes numériques et catégorielles dans deux dataframes distincts
numeric_data = data_2016[numeric_cols]
categorical_data = data_2016[categorical_cols]




# standardiser les colonnes numériques

In [785]:


# combiner les deux dataframes (numériques et catégorielles)
data_combined = pd.concat([numeric_data, categorical_data], axis=1)

In [786]:
data_combined.dtypes

freight_value          float64
review_score           float64
score_freq             float64
score_rec              float64
score_montant          float64
customer_city           object
categorie_regroupee     object
dtype: object

In [787]:
# initialiser l'algorithme K-Prototypes avec les paramètres nécessaires
kproto = KPrototypes(n_clusters=5, init='Huang',n_jobs = -1 , max_iter = 20, n_init=2, verbose=2,random_state=42)

 # entraîner le modèle sur les données combinées
clusters_2016 = kproto.fit_predict(data_combined, categorical=list(range(len(numeric_cols), data_combined.shape[1])))

# afficher les résultats
print("Cluster labels:", clusters)

Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 1, iteration: 1/20, moves: 36, ncost: 10260.269384807898
Init: initializing centroids
Init: initializing clusters
Run: 1, iteration: 2/20, moves: 50, ncost: 8862.381019360753
Starting iterations...
Run: 1, iteration: 3/20, moves: 22, ncost: 8477.062220020865
Run: 1, iteration: 4/20, moves: 10, ncost: 8455.220418207873
Run: 2, iteration: 1/20, moves: 107, ncost: 19093.640478491594
Run: 1, iteration: 5/20, moves: 7, ncost: 8439.527891965177
Run: 2, iteration: 2/20, moves: 93, ncost: 15744.548758822591
Run: 1, iteration: 6/20, moves: 11, ncost: 8403.74446239763
Run: 1, iteration: 7/20, moves: 16, ncost: 8373.498140968637
Run: 2, iteration: 3/20, moves: 47, ncost: 12659.464096647895
Run: 1, iteration: 8/20, moves: 5, ncost: 8368.488823318325
Run: 1, iteration: 9/20, moves: 3, ncost: 8366.456986879844
Run: 2, iteration: 4/20, moves: 39, ncost: 12176.55916989897
Run: 1, iteration: 10/20, moves: 3, ncost: 8363.684271229396
Run: 2, iteration: 5/20, moves: 45, ncost: 11587.435541206201
Run: 1, iteration: 11/20, moves: 10, ncost: 8344.94929451713
Run: 2, iteration: 6/20, moves: 39, ncost: 10941.59562248896
Run: 1, iteration: 12/20, moves: 4, ncost: 8340.99515538178
Run: 2, iteration: 7/20, moves: 30, ncost: 10644.104211854043
Run: 1, iteration: 13/20, moves: 3, ncost: 8339.770434318105
Run: 2, iteration: 8/20, moves: 13, ncost: 10422.480530065937
Run: 1, iteration: 14/20, moves: 0, ncost: 8339.770434318105
Run: 2, iteration: 9/20, moves: 41, ncost: 8954.130863726994
Run: 2, iteration: 10/20, moves: 49, ncost: 8529.828179929984
Run: 2, iteration: 11/20, moves: 16, ncost: 8467.6201249145
Run: 2, iteration: 12/20, moves: 7, ncost: 8455.220418207873
Run: 2, iteration: 13/20, moves: 7, ncost: 8439.527891965177
Run: 2, iteration: 14/20, moves: 11, ncost: 8403.74446239763
Run: 2, iteration: 15/20, moves: 16, ncost: 8373.498140968639
Run: 2, iteration: 16/20, moves: 5, ncost: 8368.488823318326
Run: 2, iteration: 17/20, moves: 3, ncost: 8366.456986879843
Run: 2, iteration: 18/20, moves: 3, ncost: 8363.684271229395
Run: 2, iteration: 19/20, moves: 10, ncost: 8344.94929451713
Run: 2, iteration: 20/20, moves: 4, ncost: 8340.995155381777
Best run was number 1
Cluster labels: [0 3 4 ... 0 1 0]

In [788]:
data_2016_2017 = data_2016_2017[[ 'freight_value', 'review_score', 'score_freq',
        'score_montant', 
       'customer_city', 'categorie_regroupee']]

In [789]:
import numpy as np
import pandas as pd
from kmodes.kprototypes import KPrototypes

# sélectionner les colonnes numériques et catégorielles
numeric_cols = [col for col in data_2016_2017.columns if data_2016_2017[col].dtype in [np.float64, np.int64]]
categorical_cols = [col for col in data_2016_2017.columns if data_2016_2017[col].dtype == 'object']

# séparer les colonnes numériques et catégorielles dans deux dataframes distincts
numeric_data = data_2016_2017[numeric_cols]
categorical_data = data_2016_2017[categorical_cols]






# combiner les deux dataframes (numériques et catégorielles)
data_combined = pd.concat([numeric_data, categorical_data], axis=1)

# initialiser l'algorithme K-Prototypes avec les paramètres nécessaires
kproto = KPrototypes(n_clusters=5, init='Huang',n_jobs = -1 , max_iter = 20, n_init=2, verbose=2,random_state=42)

 # entraîner le modèle sur les données combinées
clusters_2016_2017 = kproto.fit_predict(data_combined, categorical=list(range(len(numeric_cols), data_combined.shape[1])))

# afficher les résultats
print("Cluster labels:", clusters)

Init: initializing centroids
Init: initializing clusters
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Starting iterations...
Run: 2, iteration: 1/20, moves: 17300, ncost: 8886327.775769616
Run: 1, iteration: 1/20, moves: 28017, ncost: 10460171.921253279
Run: 1, iteration: 2/20, moves: 22771, ncost: 8623454.006277036
Run: 2, iteration: 2/20, moves: 27752, ncost: 7797220.976351667
Run: 1, iteration: 3/20, moves: 22142, ncost: 7264095.903109976
Run: 2, iteration: 3/20, moves: 23887, ncost: 6842629.666135688
Run: 1, iteration: 4/20, moves: 15674, ncost: 6396221.160898129
Run: 2, iteration: 4/20, moves: 15094, ncost: 6183960.996227921
Run: 1, iteration: 5/20, moves: 9315, ncost: 5896814.029015291
Run: 2, iteration: 5/20, moves: 10593, ncost: 5586429.356904731
Run: 1, iteration: 6/20, moves: 8937, ncost: 5346469.188289362
Run: 2, iteration: 6/20, moves: 10216, ncost: 5093506.877785135
Run: 1, iteration: 7/20, moves: 11042, ncost: 4966796.135678237
Run: 2, iteration: 7/20, moves: 8855, ncost: 4910034.017117905
Run: 1, iteration: 8/20, moves: 6874, ncost: 4877387.3778094845
Run: 2, iteration: 8/20, moves: 5702, ncost: 4864142.412705231
Run: 1, iteration: 9/20, moves: 4089, ncost: 4845968.170560151
Run: 2, iteration: 9/20, moves: 3335, ncost: 4834779.26025212
Run: 1, iteration: 10/20, moves: 2513, ncost: 4807591.209820865
Run: 2, iteration: 10/20, moves: 2097, ncost: 4802958.559307083
Run: 1, iteration: 11/20, moves: 2188, ncost: 4787126.834177407
Run: 2, iteration: 11/20, moves: 2386, ncost: 4780931.599116843
Run: 1, iteration: 12/20, moves: 6578, ncost: 4449375.331186144
Run: 2, iteration: 12/20, moves: 9239, ncost: 4385574.777945211
Run: 1, iteration: 13/20, moves: 18241, ncost: 4154414.5018149274
Run: 2, iteration: 13/20, moves: 16616, ncost: 4110166.9619260933
Run: 1, iteration: 14/20, moves: 10730, ncost: 3944277.453275846
Run: 2, iteration: 14/20, moves: 10499, ncost: 3920294.5163213406
Run: 1, iteration: 15/20, moves: 7820, ncost: 3836424.8725015353
Run: 2, iteration: 15/20, moves: 7102, ncost: 3818961.0321795736
Run: 1, iteration: 16/20, moves: 6115, ncost: 3716894.139907206
Run: 2, iteration: 16/20, moves: 5893, ncost: 3704976.127945329
Run: 1, iteration: 17/20, moves: 4249, ncost: 3642964.7487014513
Run: 2, iteration: 17/20, moves: 4035, ncost: 3637182.6113840803
Run: 1, iteration: 18/20, moves: 4436, ncost: 3593135.962563597
Run: 2, iteration: 18/20, moves: 4405, ncost: 3588334.360148938
Run: 1, iteration: 19/20, moves: 3233, ncost: 3565975.4545620573
Run: 2, iteration: 19/20, moves: 3072, ncost: 3564734.373395387
Run: 1, iteration: 20/20, moves: 1812, ncost: 3536785.197460812
Run: 2, iteration: 20/20, moves: 1738, ncost: 3535035.7389674955
Best run was number 2
Cluster labels: [0 3 4 ... 0 1 0]

In [790]:

import numpy as np
import pandas as pd
from kmodes.kprototypes import KPrototypes

# sélectionner les colonnes numériques et catégorielles
numeric_cols = [col for col in data_pourcent.columns if data_pourcent[col].dtype in [np.float64, np.int64]]
categorical_cols = [col for col in data_pourcent.columns if data_pourcent[col].dtype == 'object']

# séparer les colonnes numériques et catégorielles dans deux dataframes distincts
numeric_data = data_pourcent[numeric_cols]
categorical_data = data_pourcent[categorical_cols]




# standardiser les colonnes numériques
numeric_data = (numeric_data - numeric_data.mean()) / numeric_data.std()

# combiner les deux dataframes (numériques et catégorielles)
data_combined = pd.concat([numeric_data, categorical_data], axis=1)

# initialiser l'algorithme K-Prototypes avec les paramètres nécessaires
kproto = KPrototypes(n_clusters=5, init='Huang',n_jobs = -1 , max_iter = 20, n_init=2, verbose=2,random_state=42)

 # entraîner le modèle sur les données combinées
clusters_pourcent = kproto.fit_predict(data_combined, categorical=list(range(len(numeric_cols), data_combined.shape[1])))

# afficher les résultats
print("Cluster labels:", clusters)

Init: initializing centroids
Init: initializing centroids
Init: initializing clusters
Init: initializing clusters
Starting iterations...
Starting iterations...
Run: 1, iteration: 1/20, moves: 22459, ncost: 634498.6171935512
Run: 2, iteration: 1/20, moves: 23601, ncost: 604396.4655552033
Run: 1, iteration: 2/20, moves: 8326, ncost: 624837.3868128904
Run: 2, iteration: 2/20, moves: 9581, ncost: 594568.6178363217
Run: 1, iteration: 3/20, moves: 2814, ncost: 623023.588946396
Run: 2, iteration: 3/20, moves: 5980, ncost: 592609.968556724
Run: 1, iteration: 4/20, moves: 723, ncost: 621624.6181089343
Run: 2, iteration: 4/20, moves: 1200, ncost: 592420.9885278028
Run: 1, iteration: 5/20, moves: 595, ncost: 620760.0777364795
Run: 2, iteration: 5/20, moves: 188, ncost: 592388.2686644549
Run: 1, iteration: 6/20, moves: 461, ncost: 620567.8148754599
Run: 2, iteration: 6/20, moves: 123, ncost: 592372.3867264929
Run: 1, iteration: 7/20, moves: 233, ncost: 620460.2369379429
Run: 2, iteration: 7/20, moves: 61, ncost: 592368.1892614712
Run: 1, iteration: 8/20, moves: 128, ncost: 620412.607335754
Run: 2, iteration: 8/20, moves: 27, ncost: 592367.5213417255
Run: 1, iteration: 9/20, moves: 114, ncost: 620375.1990605807
Run: 2, iteration: 9/20, moves: 6, ncost: 592367.4815687261
Run: 1, iteration: 10/20, moves: 103, ncost: 620335.4826749301
Run: 2, iteration: 10/20, moves: 1, ncost: 592367.4782159935
Run: 1, iteration: 11/20, moves: 100, ncost: 620302.9417440023
Run: 2, iteration: 11/20, moves: 0, ncost: 592367.4782159935
Run: 1, iteration: 12/20, moves: 92, ncost: 620282.9076124037
Run: 1, iteration: 13/20, moves: 69, ncost: 620264.3811657721
Run: 1, iteration: 14/20, moves: 30, ncost: 620261.2947855593
Run: 1, iteration: 15/20, moves: 22, ncost: 620259.4949005722
Run: 1, iteration: 16/20, moves: 15, ncost: 620259.0955782202
Run: 1, iteration: 17/20, moves: 2, ncost: 620259.0729546219
Run: 1, iteration: 18/20, moves: 1, ncost: 620259.0607727712
Run: 1, iteration: 19/20, moves: 0, ncost: 620259.0607727712
Best run was number 2
Cluster labels: [0 3 4 ... 0 1 0]

In [791]:
adjusted_rand_score(clusters[:294], clusters_2016)

-0.0028070717074960443

In [797]:
print(clusters)

[0 3 4 ... 0 1 0]

In [798]:
print(clusters[:294])

[0 3 4 1 4 0 3 1 4 1 4 0 1 4 3 2 2 0 3 4 2 0 3 2 0 2 4 4 0 1 2 4 0 4 1 1 2
 1 0 0 2 1 1 1 2 1 2 1 1 2 2 1 3 3 3 3 2 3 1 1 1 2 1 3 3 4 0 2 3 4 2 0 0 3
 4 2 1 2 0 2 0 3 0 1 2 1 3 3 3 1 3 1 0 1 1 3 4 2 4 1 4 1 0 0 4 0 4 4 2 1 1
 4 1 2 0 4 3 4 3 4 3 4 1 1 0 4 0 0 3 4 2 1 2 1 2 0 2 1 4 0 2 0 3 4 0 3 3 2
 1 0 2 4 4 2 3 2 0 3 1 2 3 3 3 3 3 1 2 0 3 3 0 2 0 0 3 1 4 0 1 1 3 1 2 1 4
 0 1 2 4 1 4 4 3 0 4 2 0 2 3 3 4 2 3 4 0 1 2 1 4 0 4 3 1 0 2 0 2 2 0 2 4 3
 0 2 4 1 2 3 1 2 1 4 3 2 2 1 3 2 0 0 1 2 3 2 2 4 1 4 4 2 1 2 3 4 3 2 1 2 1
 3 4 0 1 3 0 0 3 4 3 0 0 2 0 3 2 2 3 4 2 4 1 1 2 4 0 0 4 4 4 2 2 1 1 2]

In [800]:
print(clusters_2016_2017[:294])

[3 0 4 4 4 4 0 0 0 0 4 4 0 4 3 0 4 0 0 3 0 4 4 3 0 4 0 4 0 0 0 1 0 0 3 4 0
 0 0 0 0 0 3 3 0 0 0 4 0 0 4 4 0 4 0 3 3 4 3 0 0 0 0 0 3 0 0 0 4 4 0 3 4 0
 3 0 4 0 3 0 3 4 0 0 2 0 4 0 0 0 4 0 0 4 0 4 0 4 4 3 4 0 4 4 0 2 0 4 0 0 4
 0 0 0 0 4 4 0 4 0 4 0 4 0 4 0 4 4 4 0 0 0 0 0 0 1 4 1 0 0 4 4 0 0 0 4 0 4
 4 0 4 0 0 4 3 0 0 4 4 0 0 0 4 4 0 4 4 0 4 0 0 0 4 4 0 0 0 4 0 0 3 0 4 0 4
 4 4 0 0 0 0 0 0 1 0 4 4 0 0 4 0 4 3 4 0 0 4 4 4 0 4 0 4 4 3 4 3 4 1 4 0 0
 4 0 0 0 0 1 0 0 0 4 4 0 0 0 0 0 4 0 0 3 0 4 0 0 0 3 4 4 0 0 0 0 3 0 1 0 4
 0 0 0 4 4 0 0 3 0 4 4 0 3 4 0 4 0 4 4 0 4 4 0 4 0 0 0 3 0 4 3 0 0 3 0]

In [792]:
adjusted_rand_score(clusters[:92791], clusters_2016_2017)

3.7691967673693646e-05

In [793]:
len(clusters_2016_2017)

92791

In [794]:
adjusted_rand_score(clusters[:83511], clusters_pourcent)

-1.049703990599178e-05

In [795]:
adjusted_rand_score(clusters_pourcent[:92791], clusters_2016_2017[:83511])

0.024269931811150662

In [796]:
adjusted_rand_score(clusters_2016, clusters_2016_2017[:294])

0.0195165845203688